# Generated by Django 5.2.10 on 2026-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("date_joined", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
